### ISSUE TITLE
Intermittent CORS issue

### ISSUE THREAD

**Issue by TheNewAutonomy** [centfinance/Cent.Dex_PoolsUI#100]
We intermittently have issues with nodes and Subgraph where our calls are rejected with CORS errors.

We should look at how we're creating service requests and why from time to time we have these CORS responses.

**Comment by tqmvt** [comment]
I've checked about how we fetch data from external sources like Subgraph, but it looks fine. I think these CORS errors are from the third-party services because their servers are sometimes off or their backend system has changed.

**Comment by TheNewAutonomy** [comment]
CORS issues have been detected from node end points and sometimes from Fleek.
We've switched the node end point to a dedicated endpoint which has CORS support correctly configured.
We've created a separate issue for replacing Fleek with a local alternatives and so this issue can be closed.
