### ISSUE TITLE
ExchangeProxy on Celo not correctly verified

### ISSUE THREAD

**Issue by TheNewAutonomy** [centfinance/Cent.Dex_PoolsUI#131]
On celo's block explorer, for the ExchangeProxy, in the write contract tab it shows the right methods, for the read contract for some reason its just error
https://explorer.celo.org/address/0x7EbE42906a5F1DD96E47E7152102A6aA0A0d2459/read-contract

**Comment by aristidesgpg** [comment]
@TheNewAutonomy Is this Symmetric.Core project and are you going to redeploy and verify?

**Comment by aristidesgpg** [comment]
@TheNewAutonomy I contacted with Celo dev team and the issue is that we are using a multidimensional array of tuples "tuple[][]" that is not supported by the library.
Currently, they open an issue and find a solution. 
  https://github.com/poanetwork/ex_abi/issues/88

**Comment by ayrat555** [comment]
hello can you please check if https://github.com/poanetwork/ex_abi/pull/89 works for you

**Comment by aristidesgpg** [comment]
Great!, it may work
