### ISSUE TITLE
Add personal APR column

### ISSUE THREAD

**Issue by TheNewAutonomy** [centfinance/Cent.Dex_PoolsUI#81]

**Comment by TheNewAutonomy** [comment]
Presently on the Rewards pools table view we show a number of columns for each pool including a Daily Rewards column which includes the number of SYMM and other tokens awarded to that pool over a 24 hour period.

What we've been asked to add is an additional column that shows how much of that pools allocation is going to the user connected. For example, there's a column showing TVL in a pool and a column showing the users liquidity in the pool. If you open a pool itself then in the top right it shows "My pool share" which is just the users percentage of overall liquidity in the pool. If a user connected holds 10% of the liquidity in a pool and that pool is being awarded 200 SYMM then the column would show 10% of 200 SYMM or 20 SYMM. This allows a user to see not only how much SYMM is going to a pool but how much SYMM they will personally be receiving.

**Comment by aristidesgpg** [comment]
@TheNewAutonomy Should I modify the value of "My pool share"?  or add a new column beside "My pool share"?
