### ISSUE TITLE
Correct css for Pools table view to render correctly at smaller screen sizes

### ISSUE THREAD

**Issue by TheNewAutonomy** [centfinance/Cent.Dex_PoolsUI#98]
The PoolsUI project in table view has a bug which means that columns are cut off at different page widths.
This is a particular problem on mobile devices that render on smaller screens.

This bounty is to correct the CSS so that columns on the page are always displayed. Columns can be disabled if necessary. Presently there is css that renders different columns at different screen sizes but this needs updating.

**Comment by talentdev2020** [comment]
@TheNewAutonomy I fixed this issue, but can't push because of permission
